use_frameworks!

platform :ios, '8.0'

target 'LGObjectiveCPro_Example' do
  pod 'LGObjectiveCPro', :path => '../'

  target 'LGObjectiveCPro_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
